general:
  M: 100000
  gamma: 1
  weights: [2.50, 2.5, 0.25, 0.09, 0.025, 250, 0.25, 0.25]
  #         w1    w2  w3      w4      w5    w6  w7    w8
  # old lamoscad: 2.5, 2.5, .25, .0025, .25, .25, .25, .25
  # new: 2.5, 2.5, 0.25, 0.0025, 0.025, 25, 0.25, 0.25
  # 2M in Obj 2 is dominated by w4 (Fs)
  nQ: 0
  DistanceMax: 10
  NumberStMax: 5
  nS: 1
  nH: 1
  nUN: 1

L_p_or_values:
  c_i: 1200
  m: inf

assets:
  vehicles:
    - helicopter
    - ship
    - icebreaker

  resources:
    - MCR
    - CDU
    - ISB

  Q_vr:
    ship:
      m: 100
      c: 1500
      i: 1200
    helicopter:
      m: 10
      c: 150
      i: 120
    icebreaker:
      m: 100
      c: 1500
      i: 1200

  C_r:
    m: 330  # CAD
    c: 125
    i: 100

  c_v:  # transport cost per kilometer by vehicle v
    helicopter: 40
    ship: 2
    icebreaker: 20

  n_vs_values:
    helicopter: 2000
    ship: 2000 # 10
    icebreaker: 2000 # 2